In [1]:
import torch

In [2]:
torch.version.cuda

'11.3'

In [3]:
torch.version

<module 'torch.version' from '/home/karthikragunath/anaconda3/envs/multi_head_re/lib/python3.8/site-packages/torch/version.py'>

In [4]:
print(torch.__version__)

1.10.1


In [2]:
from pytorch_transformers import *

In [6]:
encoder = BertModel.from_pretrained('bert-base-uncased')

In [7]:
encoder.named_parameters()

<generator object Module.named_parameters at 0x7f978dd6bba0>

In [11]:
req_grad_list = []
req_no_grad_list = []
for name, param in encoder.named_parameters():
    if '11' in name:
        req_grad_list.append((name, param.shape))
    else:
        req_no_grad_list.append((name, param.shape))

In [12]:
req_grad_list

[('encoder.layer.11.attention.self.query.weight', torch.Size([768, 768])),
 ('encoder.layer.11.attention.self.query.bias', torch.Size([768])),
 ('encoder.layer.11.attention.self.key.weight', torch.Size([768, 768])),
 ('encoder.layer.11.attention.self.key.bias', torch.Size([768])),
 ('encoder.layer.11.attention.self.value.weight', torch.Size([768, 768])),
 ('encoder.layer.11.attention.self.value.bias', torch.Size([768])),
 ('encoder.layer.11.attention.output.dense.weight', torch.Size([768, 768])),
 ('encoder.layer.11.attention.output.dense.bias', torch.Size([768])),
 ('encoder.layer.11.attention.output.LayerNorm.weight', torch.Size([768])),
 ('encoder.layer.11.attention.output.LayerNorm.bias', torch.Size([768])),
 ('encoder.layer.11.intermediate.dense.weight', torch.Size([3072, 768])),
 ('encoder.layer.11.intermediate.dense.bias', torch.Size([3072])),
 ('encoder.layer.11.output.dense.weight', torch.Size([768, 3072])),
 ('encoder.layer.11.output.dense.bias', torch.Size([768])),
 ('encode

In [13]:
req_no_grad_list

[('embeddings.word_embeddings.weight', torch.Size([30522, 768])),
 ('embeddings.position_embeddings.weight', torch.Size([512, 768])),
 ('embeddings.token_type_embeddings.weight', torch.Size([2, 768])),
 ('embeddings.LayerNorm.weight', torch.Size([768])),
 ('embeddings.LayerNorm.bias', torch.Size([768])),
 ('encoder.layer.0.attention.self.query.weight', torch.Size([768, 768])),
 ('encoder.layer.0.attention.self.query.bias', torch.Size([768])),
 ('encoder.layer.0.attention.self.key.weight', torch.Size([768, 768])),
 ('encoder.layer.0.attention.self.key.bias', torch.Size([768])),
 ('encoder.layer.0.attention.self.value.weight', torch.Size([768, 768])),
 ('encoder.layer.0.attention.self.value.bias', torch.Size([768])),
 ('encoder.layer.0.attention.output.dense.weight', torch.Size([768, 768])),
 ('encoder.layer.0.attention.output.dense.bias', torch.Size([768])),
 ('encoder.layer.0.attention.output.LayerNorm.weight', torch.Size([768])),
 ('encoder.layer.0.attention.output.LayerNorm.bias', to

In [3]:
embeddings = torch.nn.Embedding(num_embeddings = 1000, embedding_dim = 20)

In [4]:
word_to_ix = {"hello":1, "hi":2}

In [6]:
lookup_tensor = torch.tensor([word_to_ix["hello"]], dtype=torch.long)

In [7]:
lookup_tensor

tensor([1])

In [8]:
hello_embed = embeddings(lookup_tensor)

In [9]:
hello_embed

tensor([[-7.4194e-01,  7.9940e-02,  2.5017e-01, -4.3287e-01,  3.1160e-01,
         -7.5300e-04,  7.5953e-01,  1.4580e+00,  4.1279e-01, -2.9551e-01,
          1.4725e+00, -3.9782e-01,  1.8795e+00,  1.3693e+00,  1.7420e-01,
         -1.0694e+00,  1.5388e+00,  1.1607e+00,  5.9874e-01, -5.8690e-01]],
       grad_fn=<EmbeddingBackward0>)

In [10]:
lookup_tensor_2 = torch.tensor([word_to_ix["hello"], word_to_ix["hi"]], dtype=torch.long)

In [11]:
lookup_tensor_2

tensor([1, 2])

In [12]:
tensor_2_embeddings = embeddings(lookup_tensor_2)

In [13]:
tensor_2_embeddings

tensor([[-7.4194e-01,  7.9940e-02,  2.5017e-01, -4.3287e-01,  3.1160e-01,
         -7.5300e-04,  7.5953e-01,  1.4580e+00,  4.1279e-01, -2.9551e-01,
          1.4725e+00, -3.9782e-01,  1.8795e+00,  1.3693e+00,  1.7420e-01,
         -1.0694e+00,  1.5388e+00,  1.1607e+00,  5.9874e-01, -5.8690e-01],
        [ 2.6006e+00,  1.1157e-01, -9.8419e-01,  5.3793e-01, -5.1098e-01,
          3.9563e-01,  8.4242e-01,  7.0167e-01,  1.2220e+00,  3.5456e-01,
         -2.2770e-01, -8.3115e-01, -9.2951e-01,  3.9858e-01, -6.0387e-02,
          3.6298e-01, -4.9793e-01,  1.1272e+00, -7.7456e-02, -4.4773e-01]],
       grad_fn=<EmbeddingBackward0>)

In [14]:
# -- LSTM --

In [ ]:
rnn = torch.nn.LSTM(input_size=10, hidden_size=20, num_layers=3, batch_first=True)
