In [1]:
import torch

In [2]:
random_matrix = torch.rand(3, 5, 2, 5)

In [3]:
random_matrix.shape

torch.Size([3, 5, 2, 5])

In [4]:
random_embedding_matrix = torch.rand(3, 5, 7)

In [5]:
random_embedding_matrix.shape

torch.Size([3, 5, 7])

In [6]:
random_matrix

tensor([[[[0.0381, 0.8782, 0.8832, 0.7978, 0.2089],
          [0.3233, 0.7316, 0.7138, 0.3971, 0.1738]],

         [[0.5440, 0.8260, 0.7823, 0.9800, 0.9562],
          [0.1239, 0.3242, 0.2252, 0.4237, 0.7654]],

         [[0.8499, 0.3327, 0.0118, 0.7089, 0.8089],
          [0.5654, 0.1973, 0.9888, 0.5369, 0.0850]],

         [[0.5126, 0.8939, 0.7321, 0.4030, 0.4272],
          [0.4208, 0.6605, 0.5313, 0.9849, 0.7126]],

         [[0.5359, 0.5185, 0.2447, 0.6827, 0.7059],
          [0.4458, 0.7289, 0.8350, 0.0215, 0.7139]]],


        [[[0.1682, 0.9578, 0.7083, 0.3715, 0.0711],
          [0.3854, 0.5934, 0.8010, 0.7267, 0.2363]],

         [[0.9603, 0.7342, 0.8348, 0.7488, 0.6034],
          [0.8667, 0.3704, 0.1155, 0.7565, 0.4960]],

         [[0.0656, 0.2043, 0.5913, 0.6750, 0.3389],
          [0.5847, 0.7734, 0.0924, 0.7171, 0.1039]],

         [[0.9560, 0.4464, 0.7397, 0.9178, 0.0741],
          [0.7313, 0.5099, 0.5910, 0.6290, 0.7659]],

         [[0.9289, 0.7673, 0.2946, 0.0104, 0

In [7]:
random_matrix_sample = torch.rand(4, 2, 3, 2)

In [8]:
random_matrix_sample.shape

torch.Size([4, 2, 3, 2])

In [9]:
random_matrix_sample

tensor([[[[0.7392, 0.7254],
          [0.7160, 0.2459],
          [0.4531, 0.9429]],

         [[0.1307, 0.7146],
          [0.7067, 0.6683],
          [0.1177, 0.5000]]],


        [[[0.1743, 0.9003],
          [0.9295, 0.3163],
          [0.4281, 0.3725]],

         [[0.2027, 0.6532],
          [0.6405, 0.8453],
          [0.7648, 0.6304]]],


        [[[0.7170, 0.9537],
          [0.2466, 0.0392],
          [0.0140, 0.5226]],

         [[0.0495, 0.6922],
          [0.7226, 0.5604],
          [0.5355, 0.3271]]],


        [[[0.4802, 0.2988],
          [0.2134, 0.2874],
          [0.2702, 0.2094]],

         [[0.2990, 0.9068],
          [0.9665, 0.0566],
          [0.6660, 0.2179]]]])

In [11]:
from torch_geometric import nn

In [12]:
input_features = 7
output_features = 3
gcn_conv1 = nn.GCNConv(input_features, output_features)

In [13]:
gcn_conv1

GCNConv(7, 3)

In [14]:
for r_m in random_matrix_sample:
    print(r_m)

tensor([[[0.7392, 0.7254],
         [0.7160, 0.2459],
         [0.4531, 0.9429]],

        [[0.1307, 0.7146],
         [0.7067, 0.6683],
         [0.1177, 0.5000]]])
tensor([[[0.1743, 0.9003],
         [0.9295, 0.3163],
         [0.4281, 0.3725]],

        [[0.2027, 0.6532],
         [0.6405, 0.8453],
         [0.7648, 0.6304]]])
tensor([[[0.7170, 0.9537],
         [0.2466, 0.0392],
         [0.0140, 0.5226]],

        [[0.0495, 0.6922],
         [0.7226, 0.5604],
         [0.5355, 0.3271]]])
tensor([[[0.4802, 0.2988],
         [0.2134, 0.2874],
         [0.2702, 0.2094]],

        [[0.2990, 0.9068],
         [0.9665, 0.0566],
         [0.6660, 0.2179]]])


In [15]:
random_matrix_sample[0].shape

torch.Size([2, 3, 2])

In [16]:
random_matrix_sample_axis_swapped = torch.swapaxes(random_matrix_sample, -1, -2)

In [17]:
random_matrix_sample_axis_swapped

tensor([[[[0.7392, 0.7160, 0.4531],
          [0.7254, 0.2459, 0.9429]],

         [[0.1307, 0.7067, 0.1177],
          [0.7146, 0.6683, 0.5000]]],


        [[[0.1743, 0.9295, 0.4281],
          [0.9003, 0.3163, 0.3725]],

         [[0.2027, 0.6405, 0.7648],
          [0.6532, 0.8453, 0.6304]]],


        [[[0.7170, 0.2466, 0.0140],
          [0.9537, 0.0392, 0.5226]],

         [[0.0495, 0.7226, 0.5355],
          [0.6922, 0.5604, 0.3271]]],


        [[[0.4802, 0.2134, 0.2702],
          [0.2988, 0.2874, 0.2094]],

         [[0.2990, 0.9665, 0.6660],
          [0.9068, 0.0566, 0.2179]]]])

In [18]:
random_matrix_sample_axis_swapped.shape

torch.Size([4, 2, 2, 3])

In [21]:
for r_m in range(len(random_matrix_sample_axis_swapped)):
    source_list = []
    destination_list = []
    for source in range(len(random_matrix_sample_axis_swapped[r_m])):
        print(random_matrix_sample_axis_swapped[r_m][source], len(random_matrix_sample_axis_swapped[r_m][source]))
        destination = random_matrix_sample_axis_swapped[r_m][source][:source] + random_matrix_sample_axis_swapped[source + 1:]
        print(destination)
        

tensor([[0.7392, 0.7160, 0.4531],
        [0.7254, 0.2459, 0.9429]]) 2
tensor([[[[0.1743, 0.9295, 0.4281],
          [0.9003, 0.3163, 0.3725]],

         [[0.2027, 0.6405, 0.7648],
          [0.6532, 0.8453, 0.6304]]],


        [[[0.7170, 0.2466, 0.0140],
          [0.9537, 0.0392, 0.5226]],

         [[0.0495, 0.7226, 0.5355],
          [0.6922, 0.5604, 0.3271]]],


        [[[0.4802, 0.2134, 0.2702],
          [0.2988, 0.2874, 0.2094]],

         [[0.2990, 0.9665, 0.6660],
          [0.9068, 0.0566, 0.2179]]]])
tensor([[0.1307, 0.7067, 0.1177],
        [0.7146, 0.6683, 0.5000]]) 2
tensor([[[[0.7170, 0.2466, 0.0140],
          [0.9537, 0.0392, 0.5226]],

         [[0.0495, 0.7226, 0.5355],
          [0.6922, 0.5604, 0.3271]]],


        [[[0.4802, 0.2134, 0.2702],
          [0.2988, 0.2874, 0.2094]],

         [[0.2990, 0.9665, 0.6660],
          [0.9068, 0.0566, 0.2179]]]])
tensor([[0.1743, 0.9295, 0.4281],
        [0.9003, 0.3163, 0.3725]]) 2
tensor([[[[0.1743, 0.9295, 0.4281],
   

In [25]:
torch.cat(random_matrix_sample_axis_swapped[0][0][:0] ,random_matrix_sample_axis_swapped[0][0][1:])

TypeError: cat() received an invalid combination of arguments - got (Tensor, Tensor), but expected one of:
 * (tuple of Tensors tensors, int dim, *, Tensor out)
 * (tuple of Tensors tensors, name dim, *, Tensor out)
