In [2]:
import torch

In [3]:
random_matrix = torch.rand(3, 5, 2, 5)

In [4]:
random_matrix.shape

torch.Size([3, 5, 2, 5])

In [5]:
random_embedding_matrix = torch.rand(3, 5, 7)

In [6]:
random_embedding_matrix.shape

torch.Size([3, 5, 7])

In [7]:
random_matrix

tensor([[[[0.6609, 0.3117, 0.4132, 0.1824, 0.5999],
          [0.4193, 0.2716, 0.2915, 0.7123, 0.0070]],

         [[0.8955, 0.9758, 0.7991, 0.4739, 0.5948],
          [0.3324, 0.4565, 0.4425, 0.8621, 0.8973]],

         [[0.5418, 0.4255, 0.6773, 0.2943, 0.0501],
          [0.4185, 0.2598, 0.6754, 0.1338, 0.5878]],

         [[0.9902, 0.2338, 0.9680, 0.7160, 0.3629],
          [0.5636, 0.6936, 0.4577, 0.9497, 0.7110]],

         [[0.5689, 0.0322, 0.7044, 0.0701, 0.5104],
          [0.8420, 0.4137, 0.4804, 0.0684, 0.0082]]],


        [[[0.3561, 0.9790, 0.2697, 0.2121, 0.7607],
          [0.3377, 0.6760, 0.9259, 0.8865, 0.1825]],

         [[0.5376, 0.2781, 0.5169, 0.4064, 0.1010],
          [0.9637, 0.4761, 0.5293, 0.6767, 0.8654]],

         [[0.9840, 0.1978, 0.8009, 0.5150, 0.8402],
          [0.8706, 0.4886, 0.1096, 0.0494, 0.7180]],

         [[0.5536, 0.7448, 0.1231, 0.6998, 0.4481],
          [0.4962, 0.5576, 0.3873, 0.9661, 0.8733]],

         [[0.2851, 0.0431, 0.5553, 0.0389, 0

In [8]:
random_matrix_sample = torch.rand(4, 2, 3, 2)

In [9]:
random_matrix_sample.shape

torch.Size([4, 2, 3, 2])

In [10]:
random_matrix_sample

tensor([[[[0.7520, 0.7216],
          [0.9462, 0.9340],
          [0.0463, 0.0461]],

         [[0.1181, 0.0661],
          [0.5583, 0.6034],
          [0.7876, 0.9126]]],


        [[[0.7190, 0.5196],
          [0.4210, 0.2044],
          [0.7984, 0.6241]],

         [[0.2138, 0.6175],
          [0.5786, 0.4449],
          [0.1345, 0.4776]]],


        [[[0.6581, 0.2403],
          [0.0336, 0.0842],
          [0.4928, 0.4662]],

         [[0.5424, 0.7026],
          [0.1061, 0.1243],
          [0.5827, 0.9731]]],


        [[[0.9404, 0.7873],
          [0.4356, 0.0884],
          [0.3342, 0.1004]],

         [[0.2249, 0.0463],
          [0.0297, 0.7939],
          [0.8779, 0.9528]]]])

In [11]:
from torch_geometric import nn

In [12]:
input_features = 7
output_features = 3
gcn_conv1 = nn.GCNConv(input_features, output_features)

In [13]:
gcn_conv1

GCNConv(7, 3)

In [14]:
for r_m in random_matrix_sample:
    print(r_m)

tensor([[[0.7520, 0.7216],
         [0.9462, 0.9340],
         [0.0463, 0.0461]],

        [[0.1181, 0.0661],
         [0.5583, 0.6034],
         [0.7876, 0.9126]]])
tensor([[[0.7190, 0.5196],
         [0.4210, 0.2044],
         [0.7984, 0.6241]],

        [[0.2138, 0.6175],
         [0.5786, 0.4449],
         [0.1345, 0.4776]]])
tensor([[[0.6581, 0.2403],
         [0.0336, 0.0842],
         [0.4928, 0.4662]],

        [[0.5424, 0.7026],
         [0.1061, 0.1243],
         [0.5827, 0.9731]]])
tensor([[[0.9404, 0.7873],
         [0.4356, 0.0884],
         [0.3342, 0.1004]],

        [[0.2249, 0.0463],
         [0.0297, 0.7939],
         [0.8779, 0.9528]]])


In [15]:
random_matrix_sample[0].shape

torch.Size([2, 3, 2])

In [16]:
random_matrix_sample_axis_swapped = torch.swapaxes(random_matrix_sample, -1, -2)

In [17]:
random_matrix_sample_axis_swapped

tensor([[[[0.7520, 0.9462, 0.0463],
          [0.7216, 0.9340, 0.0461]],

         [[0.1181, 0.5583, 0.7876],
          [0.0661, 0.6034, 0.9126]]],


        [[[0.7190, 0.4210, 0.7984],
          [0.5196, 0.2044, 0.6241]],

         [[0.2138, 0.5786, 0.1345],
          [0.6175, 0.4449, 0.4776]]],


        [[[0.6581, 0.0336, 0.4928],
          [0.2403, 0.0842, 0.4662]],

         [[0.5424, 0.1061, 0.5827],
          [0.7026, 0.1243, 0.9731]]],


        [[[0.9404, 0.4356, 0.3342],
          [0.7873, 0.0884, 0.1004]],

         [[0.2249, 0.0297, 0.8779],
          [0.0463, 0.7939, 0.9528]]]])

In [18]:
random_matrix_sample_axis_swapped.shape

torch.Size([4, 2, 2, 3])

In [95]:
stacked_source_dest_tensors = torch.tensor([[[],[]]])
stacked_weight_tensors = torch.tensor([[]])
for r_m in range(len(random_matrix_sample_axis_swapped)):
    source_dest_tensor = torch.tensor([[],[]])
    weight_tensor = torch.tensor([])
    for source in range(len(random_matrix_sample_axis_swapped[r_m])):
        for destination in range(len(random_matrix_sample_axis_swapped[r_m][source])):
            for relation in range(len(random_matrix_sample_axis_swapped[r_m][source][destination])):
                source_dest_tensor = torch.cat((source_dest_tensor, torch.reshape(torch.tensor([source + 1, destination + 1]), (2,1))), 1)
                weight_tensor = torch.cat((weight_tensor, torch.tensor([random_matrix_sample_axis_swapped[r_m][source][destination][relation]])), 0)
    source_dest_tensor_unsqueezed = torch.unsqueeze(source_dest_tensor, dim=0)
    weight_tensor_unsqueezed = torch.unsqueeze(weight_tensor, dim=0)
    if not stacked_source_dest_tensors.numel():
        stacked_source_dest_tensors = source_dest_tensor_unsqueezed
        stacked_weight_tensors = weight_tensor_unsqueezed
    else:
        stacked_source_dest_tensors = torch.cat((stacked_source_dest_tensors, source_dest_tensor_unsqueezed), dim=0)
        stacked_weight_tensors = torch.cat((stacked_weight_tensors, weight_tensor_unsqueezed), dim=0)

In [96]:
print(stacked_source_dest_tensors.shape)

torch.Size([4, 2, 12])


In [97]:
stacked_weight_tensors.shape

torch.Size([4, 12])

In [99]:
# --------------- Rough ---------------

In [20]:
a = torch.empty((2,3), dtype=torch.int32, device = 'cuda')

In [24]:
a = torch.rand(3, 4)
b = torch.zeros(1, 4)

idx = 1

In [25]:
c = torch.cat([a[:idx], b, a[idx:]], 0)

In [26]:
a

tensor([[0.3400, 0.8049, 0.7360, 0.5542],
        [0.0220, 0.6208, 0.7575, 0.9252],
        [0.1766, 0.6195, 0.2240, 0.5277]])

In [27]:
b

tensor([[0., 0., 0., 0.]])

In [28]:
c

tensor([[0.3400, 0.8049, 0.7360, 0.5542],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0220, 0.6208, 0.7575, 0.9252],
        [0.1766, 0.6195, 0.2240, 0.5277]])

In [29]:
d = torch.cat([a[:idx], b], 0)

In [30]:
d

tensor([[0.3400, 0.8049, 0.7360, 0.5542],
        [0.0000, 0.0000, 0.0000, 0.0000]])

In [35]:
e = torch.cat([a[0], torch.tensor([1])], 0)

In [32]:
a[0].shape

torch.Size([4])

In [33]:
b.shape

torch.Size([1, 4])

In [36]:
e

tensor([0.3400, 0.8049, 0.7360, 0.5542, 1.0000])

In [37]:
a

tensor([[0.3400, 0.8049, 0.7360, 0.5542],
        [0.0220, 0.6208, 0.7575, 0.9252],
        [0.1766, 0.6195, 0.2240, 0.5277]])

In [38]:
source_dest_tensor = torch.tensor([[]]) 

In [50]:
f = torch.cat((a, torch.reshape(torch.tensor([1,2,3]), (3,1))), 1)

In [41]:
a[:0].shape

torch.Size([0, 4])

In [43]:
a[0:].shape

torch.Size([3, 4])

In [44]:
a.shape

torch.Size([3, 4])

In [52]:
h = torch.tensor([])

In [55]:
h = torch.cat((h, torch.tensor([0])), 0)

In [56]:
h

tensor([0.])

In [74]:
tensor_1 = torch.tensor([])
tensor_2 = torch.ones(2,2)

In [78]:
stacked_source_dest_tensors = torch.tensor([[],[]])
stacked_source_dest_tensors.numel()

0

In [86]:
tensor_2

tensor([[1., 1.],
        [1., 1.]])

In [89]:
torch.unsqueeze(tensor_2, dim = 0)

tensor([[[1., 1.],
         [1., 1.]]])