In [1]:
import torch

In [2]:
random_matrix = torch.rand(3, 5, 2, 5)

In [3]:
random_matrix.shape

torch.Size([3, 5, 2, 5])

In [4]:
random_embedding_matrix = torch.rand(3, 5, 7)

In [5]:
random_embedding_matrix.shape

torch.Size([3, 5, 7])

In [6]:
random_matrix

tensor([[[[0.0845, 0.8287, 0.2135, 0.3330, 0.3043],
          [0.7011, 0.3216, 0.4450, 0.6756, 0.9506]],

         [[0.9042, 0.2701, 0.0535, 0.9580, 0.1860],
          [0.4401, 0.1041, 0.1809, 0.5769, 0.7657]],

         [[0.7873, 0.9895, 0.0176, 0.8863, 0.2522],
          [0.0879, 0.4539, 0.7922, 0.4219, 0.0050]],

         [[0.9563, 0.2417, 0.9420, 0.9463, 0.2581],
          [0.7685, 0.5358, 0.4376, 0.6116, 0.1069]],

         [[0.3436, 0.2957, 0.7537, 0.8346, 0.6959],
          [0.2328, 0.7075, 0.5962, 0.6935, 0.2577]]],


        [[[0.9525, 0.7711, 0.2572, 0.0264, 0.7877],
          [0.5233, 0.6085, 0.0658, 0.7963, 0.0783]],

         [[0.9705, 0.4682, 0.4798, 0.9250, 0.6560],
          [0.2795, 0.7994, 0.4673, 0.7909, 0.2949]],

         [[0.4938, 0.6161, 0.0852, 0.4076, 0.1012],
          [0.0834, 0.4930, 0.4599, 0.8585, 0.1178]],

         [[0.0913, 0.1287, 0.2173, 0.5981, 0.4742],
          [0.8125, 0.6196, 0.2484, 0.4973, 0.8018]],

         [[0.7894, 0.5149, 0.7532, 0.7409, 0

In [7]:
random_matrix_sample = torch.rand(4, 2, 3, 2)

In [8]:
random_matrix_sample.shape

torch.Size([4, 2, 3, 2])

In [9]:
random_matrix_sample

tensor([[[[0.9466, 0.3912],
          [0.4251, 0.6154],
          [0.1027, 0.3570]],

         [[0.6383, 0.9852],
          [0.8653, 0.4193],
          [0.1917, 0.2293]]],


        [[[0.9351, 0.6478],
          [0.4428, 0.4528],
          [0.7581, 0.4261]],

         [[0.3714, 0.8447],
          [0.2622, 0.5211],
          [0.1114, 0.1816]]],


        [[[0.1594, 0.0827],
          [0.1266, 0.5469],
          [0.1064, 0.1591]],

         [[0.0215, 0.1864],
          [0.6365, 0.2466],
          [0.5897, 0.1981]]],


        [[[0.6845, 0.4809],
          [0.3882, 0.8049],
          [0.4775, 0.9000]],

         [[0.4721, 0.7695],
          [0.4817, 0.2462],
          [0.8077, 0.6356]]]])

In [10]:
from torch_geometric import nn

In [11]:
input_features = 7
output_features = 3
gcn_conv1 = nn.GCNConv(input_features, output_features)

In [12]:
gcn_conv1

GCNConv(7, 3)

In [13]:
for r_m in random_matrix_sample:
    print(r_m)

tensor([[[0.9466, 0.3912],
         [0.4251, 0.6154],
         [0.1027, 0.3570]],

        [[0.6383, 0.9852],
         [0.8653, 0.4193],
         [0.1917, 0.2293]]])
tensor([[[0.9351, 0.6478],
         [0.4428, 0.4528],
         [0.7581, 0.4261]],

        [[0.3714, 0.8447],
         [0.2622, 0.5211],
         [0.1114, 0.1816]]])
tensor([[[0.1594, 0.0827],
         [0.1266, 0.5469],
         [0.1064, 0.1591]],

        [[0.0215, 0.1864],
         [0.6365, 0.2466],
         [0.5897, 0.1981]]])
tensor([[[0.6845, 0.4809],
         [0.3882, 0.8049],
         [0.4775, 0.9000]],

        [[0.4721, 0.7695],
         [0.4817, 0.2462],
         [0.8077, 0.6356]]])


In [14]:
random_matrix_sample[0].shape

torch.Size([2, 3, 2])

In [15]:
random_matrix_sample_axis_swapped = torch.swapaxes(random_matrix_sample, -1, -2)

In [16]:
random_matrix_sample_axis_swapped

tensor([[[[0.9466, 0.4251, 0.1027],
          [0.3912, 0.6154, 0.3570]],

         [[0.6383, 0.8653, 0.1917],
          [0.9852, 0.4193, 0.2293]]],


        [[[0.9351, 0.4428, 0.7581],
          [0.6478, 0.4528, 0.4261]],

         [[0.3714, 0.2622, 0.1114],
          [0.8447, 0.5211, 0.1816]]],


        [[[0.1594, 0.1266, 0.1064],
          [0.0827, 0.5469, 0.1591]],

         [[0.0215, 0.6365, 0.5897],
          [0.1864, 0.2466, 0.1981]]],


        [[[0.6845, 0.3882, 0.4775],
          [0.4809, 0.8049, 0.9000]],

         [[0.4721, 0.4817, 0.8077],
          [0.7695, 0.2462, 0.6356]]]])

In [17]:
random_matrix_sample_axis_swapped.shape

torch.Size([4, 2, 2, 3])

In [18]:
stacked_source_dest_tensors = torch.tensor([[[],[]]])
stacked_weight_tensors = torch.tensor([[]])
for r_m in range(len(random_matrix_sample_axis_swapped)):
    source_dest_tensor = torch.tensor([[],[]])
    weight_tensor = torch.tensor([])
    for source in range(len(random_matrix_sample_axis_swapped[r_m])):
        for destination in range(len(random_matrix_sample_axis_swapped[r_m][source])):
            for relation in range(len(random_matrix_sample_axis_swapped[r_m][source][destination])):
                source_dest_tensor = torch.cat((source_dest_tensor, torch.reshape(torch.tensor([source,destination]), (2,1))), 1)
                weight_tensor = torch.cat((weight_tensor, torch.tensor([random_matrix_sample_axis_swapped[r_m][source][destination][relation]])), 0)
    source_dest_tensor_unsqueezed = torch.unsqueeze(source_dest_tensor, dim=0)
    weight_tensor_unsqueezed = torch.unsqueeze(weight_tensor, dim=0)
    if not stacked_source_dest_tensors.numel():
        stacked_source_dest_tensors = source_dest_tensor_unsqueezed
        stacked_weight_tensors = weight_tensor_unsqueezed
    else:
        stacked_source_dest_tensors = torch.cat((stacked_source_dest_tensors, source_dest_tensor_unsqueezed), dim=0)
        stacked_weight_tensors = torch.cat((stacked_weight_tensors, weight_tensor_unsqueezed), dim=0)

In [21]:
a = source_dest_tensor_unsqueezed.grad
print(a)

None


In [23]:
# stacked_source_dest_long_tensors = stacked_source_dest_tensors.to(dtype=torch.long, device='cuda')

In [24]:
# stacked_source_dest_long_tensors = stacked_source_dest_tensors.to(dtype=torch.long)
stacked_source_dest_long_tensors = stacked_source_dest_tensors.to(dtype=torch.int64)
stacked_weight_tensors = stacked_weight_tensors.to(dtype=torch.float32)

In [25]:
random_embedding = torch.rand(4, 2, 6)

In [26]:
random_embedding = random_embedding.to(dtype=torch.float32)

In [27]:
# stacked_weight_tensors = stacked_weight_tensors.to(device='cuda')
# random_embedding = random_embedding.to(device='cuda')

In [28]:
print(stacked_source_dest_long_tensors.shape)

torch.Size([4, 2, 12])


In [29]:
stacked_weight_tensors.shape

torch.Size([4, 12])

In [30]:
random_embedding

tensor([[[0.4220, 0.1018, 0.8241, 0.1119, 0.2093, 0.2192],
         [0.0227, 0.6543, 0.3533, 0.4529, 0.3985, 0.9358]],

        [[0.8118, 0.0596, 0.3051, 0.7720, 0.5624, 0.3288],
         [0.5676, 0.0967, 0.2939, 0.1046, 0.0850, 0.4960]],

        [[0.7214, 0.7386, 0.0067, 0.8224, 0.1460, 0.3136],
         [0.4132, 0.4164, 0.2357, 0.7936, 0.2435, 0.5080]],

        [[0.6637, 0.5860, 0.6666, 0.1501, 0.6349, 0.2597],
         [0.4139, 0.0842, 0.1259, 0.1615, 0.0983, 0.0268]]])

In [31]:
stacked_source_dest_tensors[0]

tensor([[0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1.]])

In [32]:
type(stacked_source_dest_tensors[0][0][0])

torch.Tensor

In [33]:
from torch_geometric import nn

In [34]:
random_embedding[0].shape

torch.Size([2, 6])

In [35]:
stacked_weight_tensors[0].shape

torch.Size([12])

In [36]:
stacked_weight_tensors[0]

tensor([0.0829, 0.0077, 0.3238, 0.6267, 0.9532, 0.4927, 0.1342, 0.5063, 0.4062,
        0.6981, 0.9172, 0.8768])

In [37]:
random_embedding[0].shape

torch.Size([2, 6])

In [38]:
random_embedding[0]

tensor([[0.4220, 0.1018, 0.8241, 0.1119, 0.2093, 0.2192],
        [0.0227, 0.6543, 0.3533, 0.4529, 0.3985, 0.9358]])

In [39]:
stacked_source_dest_long_tensors[0]

tensor([[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1]])

In [40]:
from torch_geometric.data import Data

In [41]:
data = Data(x=random_embedding[0], edge_index=stacked_source_dest_long_tensors[0], edge_weights=stacked_weight_tensors[0])

In [42]:
data.num_features

6

In [43]:
data.edge_index

tensor([[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1]])

In [44]:
data.edge_weights

tensor([0.0829, 0.0077, 0.3238, 0.6267, 0.9532, 0.4927, 0.1342, 0.5063, 0.4062,
        0.6981, 0.9172, 0.8768])

In [45]:
data.has_self_loops()

True

In [46]:
data.num_edges

12

In [47]:
data

Data(x=[2, 6], edge_index=[2, 12], edge_weights=[12])

In [48]:
gcn_conv = nn.GCNConv(in_channels=data.num_features, out_channels=5, add_self_loops=False)
# gcn_conv = nn.GCNConv(in_channels=data.num_features, out_channels=5)

In [49]:
x = gcn_conv(x = random_embedding[0], edge_index=data.edge_index, edge_weight=data.edge_weights)

In [50]:
x

tensor([[-0.0255,  0.1218, -0.1429, -0.2971, -0.0247],
        [ 0.1267,  0.3778, -0.4736, -0.6495, -0.0682]], grad_fn=<AddBackward0>)

In [51]:
from torch_geometric.loader import DataLoader

In [54]:
stacked_source_dest_tensors = torch.tensor([[[],[]]])
stacked_weight_tensors = torch.tensor([[]])
for r_m in range(len(random_matrix_sample_axis_swapped)):
    source_dest_tensor = torch.tensor([[],[]])
    weight_tensor = torch.tensor([])
    for source in range(len(random_matrix_sample_axis_swapped[r_m])):
        for destination in range(len(random_matrix_sample_axis_swapped[r_m][source])):
            for relation in range(len(random_matrix_sample_axis_swapped[r_m][source][destination])):
                source_dest_tensor = torch.cat((source_dest_tensor, torch.reshape(torch.tensor([source,destination]), (2,1))), 1)
                weight_tensor = torch.cat((weight_tensor, torch.tensor([random_matrix_sample_axis_swapped[r_m][source][destination][relation]])), 0)
    source_dest_tensor_unsqueezed = torch.unsqueeze(source_dest_tensor, dim=0)
    weight_tensor_unsqueezed = torch.unsqueeze(weight_tensor, dim=0)
    if not stacked_source_dest_tensors.numel():
        stacked_source_dest_tensors = source_dest_tensor_unsqueezed
        stacked_weight_tensors = weight_tensor_unsqueezed
    else:
        stacked_source_dest_tensors = torch.cat((stacked_source_dest_tensors, source_dest_tensor_unsqueezed), dim=0)
        stacked_weight_tensors = torch.cat((stacked_weight_tensors, weight_tensor_unsqueezed), dim=0)

stacked_source_dest_long_tensors = stacked_source_dest_tensors.to(dtype=torch.int64)
stacked_weight_tensors = stacked_weight_tensors.to(dtype=torch.float32)
random_embedding = torch.rand(4, 2, 6)
random_embedding = random_embedding.to(dtype=torch.float32)

dataset_list = []
for index in range(len(stacked_source_dest_long_tensors)):
    data = Data(x=random_embedding[index], edge_index=stacked_source_dest_long_tensors[index], edge_weights=stacked_weight_tensors[index])
    dataset_list.append(data)
batched_dataset = DataLoader(dataset_list, batch_size=2)


In [55]:
batched_dataset

In [56]:
for dataset in batched_dataset:
    print(dataset)

DataBatch(x=[4, 6], edge_index=[2, 24], edge_weights=[24], batch=[4], ptr=[3])
DataBatch(x=[4, 6], edge_index=[2, 24], edge_weights=[24], batch=[4], ptr=[3])


In [99]:
# --------------- Rough ---------------

In [20]:
a = torch.empty((2,3), dtype=torch.int32, device = 'cuda')

In [24]:
a = torch.rand(3, 4)
b = torch.zeros(1, 4)

idx = 1

In [25]:
c = torch.cat([a[:idx], b, a[idx:]], 0)

In [26]:
a

tensor([[0.3400, 0.8049, 0.7360, 0.5542],
        [0.0220, 0.6208, 0.7575, 0.9252],
        [0.1766, 0.6195, 0.2240, 0.5277]])

In [27]:
b

tensor([[0., 0., 0., 0.]])

In [28]:
c

tensor([[0.3400, 0.8049, 0.7360, 0.5542],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0220, 0.6208, 0.7575, 0.9252],
        [0.1766, 0.6195, 0.2240, 0.5277]])

In [29]:
d = torch.cat([a[:idx], b], 0)

In [30]:
d

tensor([[0.3400, 0.8049, 0.7360, 0.5542],
        [0.0000, 0.0000, 0.0000, 0.0000]])

In [35]:
e = torch.cat([a[0], torch.tensor([1])], 0)

In [32]:
a[0].shape

torch.Size([4])

In [33]:
b.shape

torch.Size([1, 4])

In [36]:
e

tensor([0.3400, 0.8049, 0.7360, 0.5542, 1.0000])

In [37]:
a

tensor([[0.3400, 0.8049, 0.7360, 0.5542],
        [0.0220, 0.6208, 0.7575, 0.9252],
        [0.1766, 0.6195, 0.2240, 0.5277]])

In [38]:
source_dest_tensor = torch.tensor([[]]) 

In [50]:
f = torch.cat((a, torch.reshape(torch.tensor([1,2,3]), (3,1))), 1)

In [41]:
a[:0].shape

torch.Size([0, 4])

In [43]:
a[0:].shape

torch.Size([3, 4])

In [44]:
a.shape

torch.Size([3, 4])

In [52]:
h = torch.tensor([])

In [55]:
h = torch.cat((h, torch.tensor([0])), 0)

In [56]:
h

tensor([0.])

In [74]:
tensor_1 = torch.tensor([])
tensor_2 = torch.ones(2,2)

In [78]:
stacked_source_dest_tensors = torch.tensor([[],[]])
stacked_source_dest_tensors.numel()

0

In [86]:
tensor_2

tensor([[1., 1.],
        [1., 1.]])

In [89]:
torch.unsqueeze(tensor_2, dim = 0)

tensor([[[1., 1.],
         [1., 1.]]])

In [112]:
x = torch.tensor(1).long()

In [113]:
x

tensor(1)

In [147]:
x = torch.LongTensor(1)

In [151]:
torch.cuda.current_device()

0

In [1]:
from torch_geometric.datasets import TUDataset
tu_dataset = TUDataset(root='/tmp/ENZYMES', name='ENZYMES', use_node_attr=True)

Extracting /tmp/ENZYMES/ENZYMES/ENZYMES.zip
Processing...
Done!


In [2]:
tu_dataset

ENZYMES(600)