In [2]:
import torch

In [3]:
random_matrix = torch.rand(3, 5, 2, 5)

In [4]:
random_matrix.shape

torch.Size([3, 5, 2, 5])

In [5]:
random_embedding_matrix = torch.rand(3, 5, 7)

In [6]:
random_embedding_matrix.shape

torch.Size([3, 5, 7])

In [7]:
random_matrix

tensor([[[[8.1576e-01, 1.6466e-01, 2.2811e-01, 7.3216e-01, 7.2075e-01],
          [3.7893e-01, 5.9991e-01, 2.7131e-01, 1.0301e-01, 4.0049e-01]],

         [[9.2903e-03, 6.5002e-01, 6.0578e-01, 7.9372e-01, 8.1719e-01],
          [7.6813e-01, 9.8997e-01, 9.5251e-01, 7.0109e-01, 5.2622e-01]],

         [[4.5722e-02, 9.5708e-02, 8.7601e-01, 5.4069e-01, 1.0572e-01],
          [8.3994e-01, 4.5181e-01, 4.5418e-01, 1.0097e-01, 5.4246e-01]],

         [[4.0870e-02, 6.3564e-01, 7.0423e-04, 9.3551e-01, 4.0099e-01],
          [1.8823e-01, 4.5103e-01, 3.3701e-01, 4.5281e-01, 3.8668e-01]],

         [[4.7575e-01, 6.7045e-01, 4.2536e-01, 5.9260e-02, 2.7956e-01],
          [6.8762e-01, 8.5209e-01, 3.2162e-01, 4.6883e-01, 5.9957e-01]]],


        [[[4.3056e-01, 5.7011e-01, 7.5427e-01, 5.6362e-01, 9.8281e-01],
          [8.5284e-01, 8.6827e-01, 9.2796e-01, 2.2699e-01, 6.9609e-01]],

         [[1.2906e-02, 6.5012e-01, 2.3826e-01, 5.4148e-01, 4.6318e-02],
          [1.2509e-02, 7.8693e-01, 3.1266e-01, 8.9

In [8]:
random_matrix_sample = torch.rand(4, 2, 3, 2)

In [9]:
random_matrix_sample.shape

torch.Size([4, 2, 3, 2])

In [10]:
random_matrix_sample

tensor([[[[7.9426e-01, 2.1193e-01],
          [6.5124e-01, 9.3037e-04],
          [8.6068e-01, 4.5537e-01]],

         [[3.4735e-02, 4.3432e-01],
          [7.8259e-01, 5.1166e-02],
          [7.6699e-01, 9.3758e-01]]],


        [[[8.3720e-01, 7.9063e-01],
          [8.0807e-01, 8.6869e-01],
          [1.6721e-01, 1.2870e-01]],

         [[5.4333e-01, 1.1210e-01],
          [9.5634e-01, 1.8790e-01],
          [3.3330e-02, 1.6191e-01]]],


        [[[2.2553e-01, 5.4298e-01],
          [2.8348e-01, 7.2627e-01],
          [7.3465e-01, 5.6206e-01]],

         [[6.8808e-01, 7.6280e-01],
          [8.6816e-02, 5.8671e-01],
          [8.0232e-01, 6.8851e-01]]],


        [[[6.2312e-01, 5.6335e-01],
          [7.8442e-01, 2.9794e-01],
          [7.3646e-01, 2.0555e-01]],

         [[1.9341e-01, 3.5527e-01],
          [4.2862e-01, 5.8753e-01],
          [3.5010e-01, 5.5785e-03]]]])

In [11]:
from torch_geometric import nn

In [12]:
input_features = 7
output_features = 3
gcn_conv1 = nn.GCNConv(input_features, output_features)

In [13]:
gcn_conv1

GCNConv(7, 3)

In [14]:
for r_m in random_matrix_sample:
    print(r_m)

tensor([[[7.9426e-01, 2.1193e-01],
         [6.5124e-01, 9.3037e-04],
         [8.6068e-01, 4.5537e-01]],

        [[3.4735e-02, 4.3432e-01],
         [7.8259e-01, 5.1166e-02],
         [7.6699e-01, 9.3758e-01]]])
tensor([[[0.8372, 0.7906],
         [0.8081, 0.8687],
         [0.1672, 0.1287]],

        [[0.5433, 0.1121],
         [0.9563, 0.1879],
         [0.0333, 0.1619]]])
tensor([[[0.2255, 0.5430],
         [0.2835, 0.7263],
         [0.7347, 0.5621]],

        [[0.6881, 0.7628],
         [0.0868, 0.5867],
         [0.8023, 0.6885]]])
tensor([[[0.6231, 0.5633],
         [0.7844, 0.2979],
         [0.7365, 0.2055]],

        [[0.1934, 0.3553],
         [0.4286, 0.5875],
         [0.3501, 0.0056]]])


In [15]:
random_matrix_sample[0].shape

torch.Size([2, 3, 2])

In [16]:
random_matrix_sample_axis_swapped = torch.swapaxes(random_matrix_sample, -1, -2)

In [17]:
random_matrix_sample_axis_swapped

tensor([[[[7.9426e-01, 6.5124e-01, 8.6068e-01],
          [2.1193e-01, 9.3037e-04, 4.5537e-01]],

         [[3.4735e-02, 7.8259e-01, 7.6699e-01],
          [4.3432e-01, 5.1166e-02, 9.3758e-01]]],


        [[[8.3720e-01, 8.0807e-01, 1.6721e-01],
          [7.9063e-01, 8.6869e-01, 1.2870e-01]],

         [[5.4333e-01, 9.5634e-01, 3.3330e-02],
          [1.1210e-01, 1.8790e-01, 1.6191e-01]]],


        [[[2.2553e-01, 2.8348e-01, 7.3465e-01],
          [5.4298e-01, 7.2627e-01, 5.6206e-01]],

         [[6.8808e-01, 8.6816e-02, 8.0232e-01],
          [7.6280e-01, 5.8671e-01, 6.8851e-01]]],


        [[[6.2312e-01, 7.8442e-01, 7.3646e-01],
          [5.6335e-01, 2.9794e-01, 2.0555e-01]],

         [[1.9341e-01, 4.2862e-01, 3.5010e-01],
          [3.5527e-01, 5.8753e-01, 5.5785e-03]]]])

In [18]:
random_matrix_sample_axis_swapped.shape

torch.Size([4, 2, 2, 3])

In [19]:
stacked_source_dest_tensors = torch.tensor([[[],[]]])
stacked_weight_tensors = torch.tensor([[]])
for r_m in range(len(random_matrix_sample_axis_swapped)):
    source_dest_tensor = torch.tensor([[],[]])
    weight_tensor = torch.tensor([])
    for source in range(len(random_matrix_sample_axis_swapped[r_m])):
        for destination in range(len(random_matrix_sample_axis_swapped[r_m][source])):
            for relation in range(len(random_matrix_sample_axis_swapped[r_m][source][destination])):
                source_dest_tensor = torch.cat((source_dest_tensor, torch.reshape(torch.tensor([source,destination]), (2,1))), 1)
                weight_tensor = torch.cat((weight_tensor, torch.tensor([random_matrix_sample_axis_swapped[r_m][source][destination][relation]])), 0)
    source_dest_tensor_unsqueezed = torch.unsqueeze(source_dest_tensor, dim=0)
    weight_tensor_unsqueezed = torch.unsqueeze(weight_tensor, dim=0)
    if not stacked_source_dest_tensors.numel():
        stacked_source_dest_tensors = source_dest_tensor_unsqueezed
        stacked_weight_tensors = weight_tensor_unsqueezed
    else:
        stacked_source_dest_tensors = torch.cat((stacked_source_dest_tensors, source_dest_tensor_unsqueezed), dim=0)
        stacked_weight_tensors = torch.cat((stacked_weight_tensors, weight_tensor_unsqueezed), dim=0)

In [20]:
a = source_dest_tensor_unsqueezed.grad
print(a)

None


In [106]:
stacked_source_dest_long_tensors = stacked_source_dest_tensors.to(dtype=torch.long, device='cuda')

In [22]:
# stacked_source_dest_long_tensors = stacked_source_dest_tensors.to(dtype=torch.long)
stacked_source_dest_long_tensors = stacked_source_dest_tensors.to(dtype=torch.int64)
stacked_weight_tensors = stacked_weight_tensors.to(dtype=torch.float32)

In [23]:
random_embedding = torch.rand(4, 2, 6)

In [24]:
random_embedding = random_embedding.to(dtype=torch.float32)

In [25]:
# stacked_weight_tensors = stacked_weight_tensors.to(device='cuda')
# random_embedding = random_embedding.to(device='cuda')

In [26]:
print(stacked_source_dest_long_tensors.shape)

torch.Size([4, 2, 12])


In [27]:
stacked_weight_tensors.shape

torch.Size([4, 12])

In [28]:
random_embedding

tensor([[[0.0153, 0.4764, 0.5792, 0.9074, 0.4270, 0.0366],
         [0.4455, 0.6412, 0.7973, 0.4140, 0.5115, 0.6130]],

        [[0.5805, 0.5897, 0.8438, 0.5232, 0.8937, 0.2336],
         [0.5762, 0.8037, 0.4904, 0.4823, 0.6909, 0.9418]],

        [[0.9925, 0.7488, 0.2942, 0.8792, 0.2319, 0.4086],
         [0.2910, 0.5968, 0.0894, 0.6777, 0.9551, 0.2706]],

        [[0.8708, 0.0733, 0.2123, 0.2315, 0.2924, 0.6151],
         [0.1349, 0.1676, 0.9906, 0.4050, 0.0171, 0.9036]]])

In [29]:
stacked_source_dest_tensors[0]

tensor([[0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1.]])

In [30]:
type(stacked_source_dest_tensors[0][0][0])

torch.Tensor

In [31]:
from torch_geometric import nn

In [32]:
random_embedding[0].shape

torch.Size([2, 6])

In [33]:
stacked_weight_tensors[0].shape

torch.Size([12])

In [34]:
stacked_weight_tensors[0]

tensor([7.9426e-01, 6.5124e-01, 8.6068e-01, 2.1193e-01, 9.3037e-04, 4.5537e-01,
        3.4735e-02, 7.8259e-01, 7.6699e-01, 4.3432e-01, 5.1166e-02, 9.3758e-01])

In [35]:
random_embedding[0].shape

torch.Size([2, 6])

In [36]:
random_embedding[0]

tensor([[0.0153, 0.4764, 0.5792, 0.9074, 0.4270, 0.0366],
        [0.4455, 0.6412, 0.7973, 0.4140, 0.5115, 0.6130]])

In [37]:
stacked_source_dest_long_tensors[0]

tensor([[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1]])

In [38]:
from torch_geometric.data import Data

In [39]:
data = Data(x=random_embedding[0], edge_index=stacked_source_dest_long_tensors[0], edge_weights=stacked_weight_tensors[0])

In [40]:
data.num_features

6

In [41]:
data.edge_index

tensor([[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1]])

In [42]:
data.edge_weights

tensor([7.9426e-01, 6.5124e-01, 8.6068e-01, 2.1193e-01, 9.3037e-04, 4.5537e-01,
        3.4735e-02, 7.8259e-01, 7.6699e-01, 4.3432e-01, 5.1166e-02, 9.3758e-01])

In [43]:
data.has_self_loops()

True

In [44]:
data.num_edges

12

In [45]:
data

Data(x=[2, 6], edge_index=[2, 12], edge_weights=[12])

In [46]:
gcn_conv = nn.GCNConv(in_channels=data.num_features, out_channels=5, add_self_loops=False)
# gcn_conv = nn.GCNConv(in_channels=data.num_features, out_channels=5)

In [47]:
x = gcn_conv(x = random_embedding[0], edge_index=data.edge_index, edge_weight=data.edge_weights)

In [48]:
x

tensor([[ 0.2695, -0.8779, -0.8333,  1.4023, -0.9468],
        [ 0.1619, -0.6241, -0.6956,  1.2191, -0.8215]], grad_fn=<AddBackward0>)

In [49]:
from torch_geometric.loader import DataLoader

In [50]:
stacked_source_dest_tensors = torch.tensor([[[],[]]])
stacked_weight_tensors = torch.tensor([[]])
for r_m in range(len(random_matrix_sample_axis_swapped)):
    source_dest_tensor = torch.tensor([[],[]])
    weight_tensor = torch.tensor([])
    for source in range(len(random_matrix_sample_axis_swapped[r_m])):
        for destination in range(len(random_matrix_sample_axis_swapped[r_m][source])):
            for relation in range(len(random_matrix_sample_axis_swapped[r_m][source][destination])):
                source_dest_tensor = torch.cat((source_dest_tensor, torch.reshape(torch.tensor([source,destination]), (2,1))), 1)
                weight_tensor = torch.cat((weight_tensor, torch.tensor([random_matrix_sample_axis_swapped[r_m][source][destination][relation]])), 0)
    source_dest_tensor_unsqueezed = torch.unsqueeze(source_dest_tensor, dim=0)
    weight_tensor_unsqueezed = torch.unsqueeze(weight_tensor, dim=0)
    if not stacked_source_dest_tensors.numel():
        stacked_source_dest_tensors = source_dest_tensor_unsqueezed
        stacked_weight_tensors = weight_tensor_unsqueezed
    else:
        stacked_source_dest_tensors = torch.cat((stacked_source_dest_tensors, source_dest_tensor_unsqueezed), dim=0)
        stacked_weight_tensors = torch.cat((stacked_weight_tensors, weight_tensor_unsqueezed), dim=0)

stacked_source_dest_long_tensors = stacked_source_dest_tensors.to(dtype=torch.int64)
stacked_weight_tensors = stacked_weight_tensors.to(dtype=torch.float32)
random_embedding = torch.rand(4, 2, 6)
random_embedding = random_embedding.to(dtype=torch.float32)

dataset_list = []
for index in range(len(stacked_source_dest_long_tensors)):
    data = Data(x=random_embedding[index], edge_index=stacked_source_dest_long_tensors[index], edge_weights=stacked_weight_tensors[index])
    dataset_list.append(data)
batched_dataset = DataLoader(dataset_list, batch_size=2)


In [51]:
batched_dataset

In [52]:
for dataset in batched_dataset:
    print(dataset)

DataBatch(x=[4, 6], edge_index=[2, 24], edge_weights=[24], batch=[4], ptr=[3])
DataBatch(x=[4, 6], edge_index=[2, 24], edge_weights=[24], batch=[4], ptr=[3])


In [111]:
for dataset in batched_dataset:
    print(dataset.x.get_device(), dataset.edge_index.get_device(), dataset.edge_weights.get_device())
    x = gcn_conv(x = dataset.x, edge_index=dataset.edge_index, edge_weight=dataset.edge_weights)
    print(x.shape)

-1 -1 -1
torch.Size([4, 5])
-1 -1 -1
torch.Size([4, 5])


In [72]:
# concatenated_batches = torch.empty((2,2,5))
concatenated_batches = torch.tensor([])
for dataset in batched_dataset:
    x = gcn_conv(x = dataset.x, edge_index=dataset.edge_index, edge_weight=dataset.edge_weights)
    y = torch.reshape(x, (-1, 2, 5))
    if not concatenated_batches.numel():
        concatenated_batches = y
    else:
        concatenated_batches = torch.cat((concatenated_batches, y), dim=0)
    print(x, y, y.shape, concatenated_batches.shape)

tensor([[ 0.0421, -0.3052, -1.3759,  1.4789, -1.3269],
        [ 0.0774, -0.1094, -1.1422,  0.9927, -1.1534],
        [-0.0050, -0.7100, -0.8903,  1.6072, -0.8738],
        [-0.0744, -0.5218, -0.7591,  1.3438, -0.6906]], grad_fn=<AddBackward0>) tensor([[[ 0.0421, -0.3052, -1.3759,  1.4789, -1.3269],
         [ 0.0774, -0.1094, -1.1422,  0.9927, -1.1534]],

        [[-0.0050, -0.7100, -0.8903,  1.6072, -0.8738],
         [-0.0744, -0.5218, -0.7591,  1.3438, -0.6906]]],
       grad_fn=<ReshapeAliasBackward0>) torch.Size([2, 2, 5]) torch.Size([2, 2, 5])
tensor([[-0.0200, -0.3361, -0.9285,  1.1167, -0.8154],
        [-0.0432, -0.3982, -1.0855,  1.3312, -0.9318],
        [-0.1077, -0.4778, -0.9929,  1.3191, -0.6882],
        [-0.0584, -0.3743, -0.7823,  1.0327, -0.5894]], grad_fn=<AddBackward0>) tensor([[[-0.0200, -0.3361, -0.9285,  1.1167, -0.8154],
         [-0.0432, -0.3982, -1.0855,  1.3312, -0.9318]],

        [[-0.1077, -0.4778, -0.9929,  1.3191, -0.6882],
         [-0.0584, -0.3743, 

In [58]:
for i in range(len(random_embedding)):
    data = Data(x=random_embedding[i], edge_index=stacked_source_dest_long_tensors[i], edge_weights=stacked_weight_tensors[i])
    x = gcn_conv(x = data.x, edge_index=data.edge_index, edge_weight=data.edge_weights)
    print(x)

tensor([[ 0.0421, -0.3052, -1.3759,  1.4789, -1.3269],
        [ 0.0774, -0.1094, -1.1422,  0.9927, -1.1534]], grad_fn=<AddBackward0>)
tensor([[-0.0050, -0.7100, -0.8903,  1.6072, -0.8738],
        [-0.0744, -0.5218, -0.7591,  1.3438, -0.6906]], grad_fn=<AddBackward0>)
tensor([[-0.0200, -0.3361, -0.9285,  1.1167, -0.8154],
        [-0.0432, -0.3982, -1.0855,  1.3312, -0.9318]], grad_fn=<AddBackward0>)
tensor([[-0.1077, -0.4778, -0.9929,  1.3191, -0.6882],
        [-0.0584, -0.3743, -0.7823,  1.0327, -0.5894]], grad_fn=<AddBackward0>)


In [107]:
for dataset in batched_dataset:
    dataset.to(device='cuda')
    print(dataset.num_nodes)

4
4


In [80]:
len(random_embedding[0][0])

6

In [81]:
concatenated_batches.shape

torch.Size([4, 2, 5])

In [105]:
type(concatenated_batches.shape[0])

int

In [86]:
batch_size = len(concatenated_batches)
seq_len = len(concatenated_batches[0])
num_features = len(concatenated_batches[0][0])

num_layers = 1
num_directions = 2
output_size = len(concatenated_batches[0][0])

input = concatenated_batches
hidden = torch.randn(num_layers * num_directions, batch_size, output_size)
cell_state = torch.randn(num_layers * num_directions, batch_size, output_size)
cell = torch.nn.LSTM(input_size = num_features, hidden_size = output_size, batch_first = True, num_layers=1, bidirectional=True)

out, hidden = cell(input, (hidden, cell_state))

In [87]:
# rnn = nn.LSTM(10, 20, 2)
# input = torch.randn(5, 3, 10)
# h0 = torch.randn(2, 3, 20)
# c0 = torch.randn(2, 3, 20)
# output, (hn, cn) = rnn(input, (h0, c0))

In [88]:
out.shape

torch.Size([4, 2, 10])

In [92]:
hidden

(tensor([[[-0.0701, -0.0984, -0.1751, -0.1928, -0.1568],
          [-0.1548, -0.2780,  0.2074, -0.2525, -0.0399],
          [-0.0371,  0.3200,  0.4437, -0.2267, -0.2245],
          [-0.0351,  0.3551, -0.2270, -0.2853, -0.2405]],
 
         [[-0.1288,  0.0036, -0.0282,  0.0419,  0.2395],
          [-0.1016,  0.1106, -0.0242,  0.0443,  0.1908],
          [-0.1136, -0.0025, -0.0601, -0.0023,  0.1708],
          [-0.1062, -0.1079,  0.0220,  0.0560,  0.2136]]],
        grad_fn=<StackBackward0>),
 tensor([[[-0.1788, -0.1770, -0.4030, -0.3803, -0.3624],
          [-0.5810, -0.4729,  0.3874, -0.4670, -0.0994],
          [-0.1013,  0.5025,  1.5445, -0.4340, -0.5234],
          [-0.0770,  0.6216, -0.5805, -0.4941, -0.5362]],
 
         [[-0.2687,  0.0105, -0.1053,  0.2740,  0.5939],
          [-0.1896,  0.3604, -0.1150,  0.2396,  0.4901],
          [-0.2155, -0.0065, -0.2349, -0.0115,  0.4487],
          [-0.2116, -0.3008,  0.0894,  0.3007,  0.6301]]],
        grad_fn=<StackBackward0>))

In [94]:
hidden[0].shape

torch.Size([2, 4, 5])

In [93]:
out

tensor([[[ 0.0083,  0.0191, -0.4402, -0.1113, -0.0858, -0.1288,  0.0036,
          -0.0282,  0.0419,  0.2395],
         [-0.0701, -0.0984, -0.1751, -0.1928, -0.1568, -0.2036,  0.0543,
          -0.0382,  0.0146,  0.2814]],

        [[-0.1020, -0.1818,  0.1826, -0.1636,  0.1667, -0.1016,  0.1106,
          -0.0242,  0.0443,  0.1908],
         [-0.1548, -0.2780,  0.2074, -0.2525, -0.0399, -0.1215,  0.2198,
          -0.0546,  0.0047,  0.1573]],

        [[ 0.1607,  0.4260,  0.3324, -0.1557, -0.2084, -0.1136, -0.0025,
          -0.0601, -0.0023,  0.1708],
         [-0.0371,  0.3200,  0.4437, -0.2267, -0.2245, -0.0868,  0.0224,
          -0.1330, -0.0610,  0.0519]],

        [[ 0.1804,  0.5603, -0.1768, -0.3297, -0.2493, -0.1062, -0.1079,
           0.0220,  0.0560,  0.2136],
         [-0.0351,  0.3551, -0.2270, -0.2853, -0.2405, -0.1471, -0.1588,
           0.1253,  0.0114,  0.3071]]], grad_fn=<TransposeBackward0>)

In [101]:
actual_output = out[:,-1,:]
actual_output_unsqueezed = actual_output.unsqueeze(dim=1)

In [102]:
actual_output.shape

torch.Size([4, 10])

In [103]:
actual_output_unsqueezed.shape

torch.Size([4, 1, 10])

In [99]:
# --------------- Rough ---------------

In [20]:
a = torch.empty((2,3), dtype=torch.int32, device = 'cuda')

In [24]:
a = torch.rand(3, 4)
b = torch.zeros(1, 4)

idx = 1

In [25]:
c = torch.cat([a[:idx], b, a[idx:]], 0)

In [26]:
a

tensor([[0.3400, 0.8049, 0.7360, 0.5542],
        [0.0220, 0.6208, 0.7575, 0.9252],
        [0.1766, 0.6195, 0.2240, 0.5277]])

In [27]:
b

tensor([[0., 0., 0., 0.]])

In [28]:
c

tensor([[0.3400, 0.8049, 0.7360, 0.5542],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0220, 0.6208, 0.7575, 0.9252],
        [0.1766, 0.6195, 0.2240, 0.5277]])

In [29]:
d = torch.cat([a[:idx], b], 0)

In [30]:
d

tensor([[0.3400, 0.8049, 0.7360, 0.5542],
        [0.0000, 0.0000, 0.0000, 0.0000]])

In [35]:
e = torch.cat([a[0], torch.tensor([1])], 0)

In [32]:
a[0].shape

torch.Size([4])

In [33]:
b.shape

torch.Size([1, 4])

In [36]:
e

tensor([0.3400, 0.8049, 0.7360, 0.5542, 1.0000])

In [37]:
a

tensor([[0.3400, 0.8049, 0.7360, 0.5542],
        [0.0220, 0.6208, 0.7575, 0.9252],
        [0.1766, 0.6195, 0.2240, 0.5277]])

In [38]:
source_dest_tensor = torch.tensor([[]]) 

In [50]:
f = torch.cat((a, torch.reshape(torch.tensor([1,2,3]), (3,1))), 1)

In [41]:
a[:0].shape

torch.Size([0, 4])

In [43]:
a[0:].shape

torch.Size([3, 4])

In [44]:
a.shape

torch.Size([3, 4])

In [52]:
h = torch.tensor([])

In [55]:
h = torch.cat((h, torch.tensor([0])), 0)

In [56]:
h

tensor([0.])

In [74]:
tensor_1 = torch.tensor([])
tensor_2 = torch.ones(2,2)

In [78]:
stacked_source_dest_tensors = torch.tensor([[],[]])
stacked_source_dest_tensors.numel()

0

In [86]:
tensor_2

tensor([[1., 1.],
        [1., 1.]])

In [89]:
torch.unsqueeze(tensor_2, dim = 0)

tensor([[[1., 1.],
         [1., 1.]]])

In [112]:
x = torch.tensor(1).long()

In [113]:
x

tensor(1)

In [147]:
x = torch.LongTensor(1)

In [151]:
torch.cuda.current_device()

0

In [1]:
from torch_geometric.datasets import TUDataset
tu_dataset = TUDataset(root='/tmp/ENZYMES', name='ENZYMES', use_node_attr=True)

Extracting /tmp/ENZYMES/ENZYMES/ENZYMES.zip
Processing...
Done!


In [2]:
tu_dataset

ENZYMES(600)